---
title: "Interactive maps"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  github_document:
    toc: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "readme-figs/"
)
```

### Goal

To create interactive maps of blood and feather samples for our target taxa for the Bird Genoscape Project website

### Data

The data for this project is housed in the `./data` directory. 

### Loading all required packages

```{r read-one-snppit}
library(tidyverse)
library(sf)
library(leaflet)
library(mapview)
library(ggplot2)
```

### Reading data in

```{r read-all-snppit}
COYE <- read_sf("data/COYE/COYE.shp")
as_tibble(COYE)
COYE$Range[(as.numeric(as.character(COYE$SEASONAL)) %% 10) == 2] <- "Breeding Resident"
COYE$Range[(as.numeric(as.character(COYE$SEASONAL)) %% 10) == 1] <- "Permanent Resident"
COYE$Range[(as.numeric(as.character(COYE$SEASONAL)) %% 10) == 5] <- "Wintering Resident"
COYE$Range[(as.numeric(as.character(COYE$SEASONAL)) %% 10) == 4] <- "Passage Migrant"

coyeblood <- read.csv("data/coye_blood.csv", header=T)
Blood <- st_as_sf(coyeblood, 
                  coords = c("Lon", "Lat"),
                  crs = (4326))

coyefeather <- read.csv("data/coye_feathers.csv", header=T)
Feather <- st_as_sf(coyefeather, 
                  coords = c("Lon", "Lat"),
                  crs = (4326))
```

### Create interactive maps using mapview

```{r meta-probs}
COYEmap <- mapView(COYE, map.type = "Esri.WorldShadedRelief", zcol="Range", legend=T, alpha.regions = 1)+
  mapView(Blood, map.type = "Esri.WorldShadedRelief", zcol="Stage", legend=T)+
  mapView(Feather, map.type = "Esri.WorldShadedRelief", zcol="Stage", legend=T)

COYEmap 

mapshot(COYEmap, url = "COYE_map.html")
```